# 服务配置
server:
  port: 8080
  servlet:
    context-path: /superboot

spring:
  # 读取配置文件
  profiles:
    include: redis-prod,logging,exception,mysql-prod,mybatis,mongo,elasticsearch,shiro,wechat,sms,common
    
