# 服务配置
server:
  port: 8080
  # port: 8443
  # http: 8080
  servlet:
    context-path: /superboot
    #ssl:
    #enabled: true
    #key-store: classpath:ssl/keystore.p12
    #key-store-type: PKCS12
    #key-store-password: lihaoqi
    #http2:
    # 开启http2
    #enabled: true
spring:
  # 读取配置文件
  profiles:
    include: redis-dev,logging-dev,exception,mysql-dev,mybatis,mongo,elasticsearch,shiro,wechat,sms,common,socket,api
    
